/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was aligned with the current file-route structure and can be regenerated by TanStack Router.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as HealthRouteImport } from "./routes/health";
import { Route as RoomRoomIdRouteImport } from "./routes/room/$roomId";
import { Route as ApiRoomsRouteImport } from "./routes/api/rooms";
import { Route as ApiRoomsRoomIdSnapshotRouteImport } from "./routes/api/rooms/$roomId/snapshot";
import { Route as ApiRoomsRoomIdIntentsRouteImport } from "./routes/api/rooms/$roomId/intents";
import { Route as ApiRoomsRoomIdEventsRouteImport } from "./routes/api/rooms/$roomId/events";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: "/health",
  path: "/health",
  getParentRoute: () => rootRouteImport,
} as any);
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: "/room/$roomId",
  path: "/room/$roomId",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRoomsRoute = ApiRoomsRouteImport.update({
  id: "/api/rooms",
  path: "/api/rooms",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRoomsRoomIdSnapshotRoute = ApiRoomsRoomIdSnapshotRouteImport.update({
  id: "/$roomId/snapshot",
  path: "/$roomId/snapshot",
  getParentRoute: () => ApiRoomsRoute,
} as any);
const ApiRoomsRoomIdIntentsRoute = ApiRoomsRoomIdIntentsRouteImport.update({
  id: "/$roomId/intents",
  path: "/$roomId/intents",
  getParentRoute: () => ApiRoomsRoute,
} as any);
const ApiRoomsRoomIdEventsRoute = ApiRoomsRoomIdEventsRouteImport.update({
  id: "/$roomId/events",
  path: "/$roomId/events",
  getParentRoute: () => ApiRoomsRoute,
} as any);

const ApiRoomsRouteChildren = {
  ApiRoomsRoomIdSnapshotRoute,
  ApiRoomsRoomIdIntentsRoute,
  ApiRoomsRoomIdEventsRoute,
};

const ApiRoomsRouteWithChildren = ApiRoomsRoute._addFileChildren(ApiRoomsRouteChildren);

export const routeTree = rootRouteImport._addFileChildren({
  IndexRoute,
  HealthRoute,
  RoomRoomIdRoute,
  ApiRoomsRoute: ApiRoomsRouteWithChildren,
});

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/health": typeof HealthRoute;
  "/room/$roomId": typeof RoomRoomIdRoute;
  "/api/rooms": typeof ApiRoomsRouteWithChildren;
  "/api/rooms/$roomId/events": typeof ApiRoomsRoomIdEventsRoute;
  "/api/rooms/$roomId/intents": typeof ApiRoomsRoomIdIntentsRoute;
  "/api/rooms/$roomId/snapshot": typeof ApiRoomsRoomIdSnapshotRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/health": typeof HealthRoute;
  "/room/$roomId": typeof RoomRoomIdRoute;
  "/api/rooms": typeof ApiRoomsRouteWithChildren;
  "/api/rooms/$roomId/events": typeof ApiRoomsRoomIdEventsRoute;
  "/api/rooms/$roomId/intents": typeof ApiRoomsRoomIdIntentsRoute;
  "/api/rooms/$roomId/snapshot": typeof ApiRoomsRoomIdSnapshotRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/health": typeof HealthRoute;
  "/room/$roomId": typeof RoomRoomIdRoute;
  "/api/rooms": typeof ApiRoomsRouteWithChildren;
  "/api/rooms/$roomId/events": typeof ApiRoomsRoomIdEventsRoute;
  "/api/rooms/$roomId/intents": typeof ApiRoomsRoomIdIntentsRoute;
  "/api/rooms/$roomId/snapshot": typeof ApiRoomsRoomIdSnapshotRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/health"
    | "/room/$roomId"
    | "/api/rooms"
    | "/api/rooms/$roomId/events"
    | "/api/rooms/$roomId/intents"
    | "/api/rooms/$roomId/snapshot";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/health"
    | "/room/$roomId"
    | "/api/rooms"
    | "/api/rooms/$roomId/events"
    | "/api/rooms/$roomId/intents"
    | "/api/rooms/$roomId/snapshot";
  id:
    | "__root__"
    | "/"
    | "/health"
    | "/room/$roomId"
    | "/api/rooms"
    | "/api/rooms/$roomId/events"
    | "/api/rooms/$roomId/intents"
    | "/api/rooms/$roomId/snapshot";
  fileRoutesById: FileRoutesById;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/health": {
      id: "/health";
      path: "/health";
      fullPath: "/health";
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/room/$roomId": {
      id: "/room/$roomId";
      path: "/room/$roomId";
      fullPath: "/room/$roomId";
      preLoaderRoute: typeof RoomRoomIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/rooms": {
      id: "/api/rooms";
      path: "/api/rooms";
      fullPath: "/api/rooms";
      preLoaderRoute: typeof ApiRoomsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/rooms/$roomId/events": {
      id: "/$roomId/events";
      path: "/$roomId/events";
      fullPath: "/api/rooms/$roomId/events";
      preLoaderRoute: typeof ApiRoomsRoomIdEventsRouteImport;
      parentRoute: typeof ApiRoomsRoute;
    };
    "/api/rooms/$roomId/intents": {
      id: "/$roomId/intents";
      path: "/$roomId/intents";
      fullPath: "/api/rooms/$roomId/intents";
      preLoaderRoute: typeof ApiRoomsRoomIdIntentsRouteImport;
      parentRoute: typeof ApiRoomsRoute;
    };
    "/api/rooms/$roomId/snapshot": {
      id: "/$roomId/snapshot";
      path: "/$roomId/snapshot";
      fullPath: "/api/rooms/$roomId/snapshot";
      preLoaderRoute: typeof ApiRoomsRoomIdSnapshotRouteImport;
      parentRoute: typeof ApiRoomsRoute;
    };
  }
}
